//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPLOI_DU_TEMPS_IHM.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_Cours", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_Cours : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idCoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string heuredebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string heurefinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string professeurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matiereField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idCours {
            get {
                return this.idCoursField;
            }
            set {
                if ((this.idCoursField.Equals(value) != true)) {
                    this.idCoursField = value;
                    this.RaisePropertyChanged("idCours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string heuredebut {
            get {
                return this.heuredebutField;
            }
            set {
                if ((object.ReferenceEquals(this.heuredebutField, value) != true)) {
                    this.heuredebutField = value;
                    this.RaisePropertyChanged("heuredebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string heurefin {
            get {
                return this.heurefinField;
            }
            set {
                if ((object.ReferenceEquals(this.heurefinField, value) != true)) {
                    this.heurefinField = value;
                    this.RaisePropertyChanged("heurefin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jour {
            get {
                return this.jourField;
            }
            set {
                if ((object.ReferenceEquals(this.jourField, value) != true)) {
                    this.jourField = value;
                    this.RaisePropertyChanged("jour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string professeur {
            get {
                return this.professeurField;
            }
            set {
                if ((object.ReferenceEquals(this.professeurField, value) != true)) {
                    this.professeurField = value;
                    this.RaisePropertyChanged("professeur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string salle {
            get {
                return this.salleField;
            }
            set {
                if ((object.ReferenceEquals(this.salleField, value) != true)) {
                    this.salleField = value;
                    this.RaisePropertyChanged("salle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string matiere {
            get {
                return this.matiereField;
            }
            set {
                if ((object.ReferenceEquals(this.matiereField, value) != true)) {
                    this.matiereField = value;
                    this.RaisePropertyChanged("matiere");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Get_Presence_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Get_Presence_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        private int idCoursField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idCours {
            get {
                return this.idCoursField;
            }
            set {
                if ((this.idCoursField.Equals(value) != true)) {
                    this.idCoursField = value;
                    this.RaisePropertyChanged("idCours");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_Utilisateurs", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_Utilisateurs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idUtilisateursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idUtilisateurs {
            get {
                return this.idUtilisateursField;
            }
            set {
                if ((this.idUtilisateursField.Equals(value) != true)) {
                    this.idUtilisateursField = value;
                    this.RaisePropertyChanged("idUtilisateurs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name DonneCoursResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonneCours", ReplyAction="*")]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponse DonneCours(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonneCours", ReplyAction="*")]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponse> DonneCoursAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest request);
        
        // CODEGEN: Generating message contract since element name DONNEPRESENCEAVECIDCOURSResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DONNEPRESENCEAVECIDCOURS", ReplyAction="*")]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponse DONNEPRESENCEAVECIDCOURS(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DONNEPRESENCEAVECIDCOURS", ReplyAction="*")]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponse> DONNEPRESENCEAVECIDCOURSAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest request);
        
        // CODEGEN: Generating message contract since element name DonneUtilisateursResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonneUtilisateurs", ReplyAction="*")]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponse DonneUtilisateurs(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonneUtilisateurs", ReplyAction="*")]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponse> DonneUtilisateursAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest request);
        
        // CODEGEN: Generating message contract since element name Nom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_User", ReplyAction="*")]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponse Add_User(EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_User", ReplyAction="*")]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponse> Add_UserAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest request);
        
        // CODEGEN: Generating message contract since element name AddPresenceResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPresence", ReplyAction="*")]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponse AddPresence(EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPresence", ReplyAction="*")]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponse> AddPresenceAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest request);
        
        // CODEGEN: Generating message contract since element name SupprimePresenceResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupprimePresence", ReplyAction="*")]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponse SupprimePresence(EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupprimePresence", ReplyAction="*")]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponse> SupprimePresenceAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DonneCoursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DonneCours", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequestBody Body;
        
        public DonneCoursRequest() {
        }
        
        public DonneCoursRequest(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DonneCoursRequestBody {
        
        public DonneCoursRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DonneCoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DonneCoursResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponseBody Body;
        
        public DonneCoursResponse() {
        }
        
        public DonneCoursResponse(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DonneCoursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Cours[] DonneCoursResult;
        
        public DonneCoursResponseBody() {
        }
        
        public DonneCoursResponseBody(EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Cours[] DonneCoursResult) {
            this.DonneCoursResult = DonneCoursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DONNEPRESENCEAVECIDCOURSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DONNEPRESENCEAVECIDCOURS", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequestBody Body;
        
        public DONNEPRESENCEAVECIDCOURSRequest() {
        }
        
        public DONNEPRESENCEAVECIDCOURSRequest(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DONNEPRESENCEAVECIDCOURSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int P_Id;
        
        public DONNEPRESENCEAVECIDCOURSRequestBody() {
        }
        
        public DONNEPRESENCEAVECIDCOURSRequestBody(int P_Id) {
            this.P_Id = P_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DONNEPRESENCEAVECIDCOURSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DONNEPRESENCEAVECIDCOURSResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponseBody Body;
        
        public DONNEPRESENCEAVECIDCOURSResponse() {
        }
        
        public DONNEPRESENCEAVECIDCOURSResponse(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DONNEPRESENCEAVECIDCOURSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.Get_Presence_Result[] DONNEPRESENCEAVECIDCOURSResult;
        
        public DONNEPRESENCEAVECIDCOURSResponseBody() {
        }
        
        public DONNEPRESENCEAVECIDCOURSResponseBody(EMPLOI_DU_TEMPS_IHM.ServiceReference1.Get_Presence_Result[] DONNEPRESENCEAVECIDCOURSResult) {
            this.DONNEPRESENCEAVECIDCOURSResult = DONNEPRESENCEAVECIDCOURSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DonneUtilisateursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DonneUtilisateurs", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequestBody Body;
        
        public DonneUtilisateursRequest() {
        }
        
        public DonneUtilisateursRequest(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DonneUtilisateursRequestBody {
        
        public DonneUtilisateursRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DonneUtilisateursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DonneUtilisateursResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponseBody Body;
        
        public DonneUtilisateursResponse() {
        }
        
        public DonneUtilisateursResponse(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DonneUtilisateursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Utilisateurs[] DonneUtilisateursResult;
        
        public DonneUtilisateursResponseBody() {
        }
        
        public DonneUtilisateursResponseBody(EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Utilisateurs[] DonneUtilisateursResult) {
            this.DonneUtilisateursResult = DonneUtilisateursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_User", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequestBody Body;
        
        public Add_UserRequest() {
        }
        
        public Add_UserRequest(EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Prenom;
        
        public Add_UserRequestBody() {
        }
        
        public Add_UserRequestBody(string Nom, string Prenom) {
            this.Nom = Nom;
            this.Prenom = Prenom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponseBody Body;
        
        public Add_UserResponse() {
        }
        
        public Add_UserResponse(EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Utilisateurs[] Add_UserResult;
        
        public Add_UserResponseBody() {
        }
        
        public Add_UserResponseBody(EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Utilisateurs[] Add_UserResult) {
            this.Add_UserResult = Add_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPresenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPresence", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequestBody Body;
        
        public AddPresenceRequest() {
        }
        
        public AddPresenceRequest(EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPresenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id_User;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id_Cours_Choisi;
        
        public AddPresenceRequestBody() {
        }
        
        public AddPresenceRequestBody(int Id_User, int Id_Cours_Choisi) {
            this.Id_User = Id_User;
            this.Id_Cours_Choisi = Id_Cours_Choisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPresenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPresenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponseBody Body;
        
        public AddPresenceResponse() {
        }
        
        public AddPresenceResponse(EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPresenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddPresenceResult;
        
        public AddPresenceResponseBody() {
        }
        
        public AddPresenceResponseBody(string AddPresenceResult) {
            this.AddPresenceResult = AddPresenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupprimePresenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupprimePresence", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequestBody Body;
        
        public SupprimePresenceRequest() {
        }
        
        public SupprimePresenceRequest(EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SupprimePresenceRequestBody {
        
        public SupprimePresenceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SupprimePresenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SupprimePresenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponseBody Body;
        
        public SupprimePresenceResponse() {
        }
        
        public SupprimePresenceResponse(EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SupprimePresenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SupprimePresenceResult;
        
        public SupprimePresenceResponseBody() {
        }
        
        public SupprimePresenceResponseBody(string SupprimePresenceResult) {
            this.SupprimePresenceResult = SupprimePresenceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap>, EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponse EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.DonneCours(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest request) {
            return base.Channel.DonneCours(request);
        }
        
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Cours[] DonneCours() {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequestBody();
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponse retVal = ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).DonneCours(inValue);
            return retVal.Body.DonneCoursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponse> EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.DonneCoursAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest request) {
            return base.Channel.DonneCoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursResponse> DonneCoursAsync() {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneCoursRequestBody();
            return ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).DonneCoursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponse EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.DONNEPRESENCEAVECIDCOURS(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest request) {
            return base.Channel.DONNEPRESENCEAVECIDCOURS(request);
        }
        
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.Get_Presence_Result[] DONNEPRESENCEAVECIDCOURS(int P_Id) {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequestBody();
            inValue.Body.P_Id = P_Id;
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponse retVal = ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).DONNEPRESENCEAVECIDCOURS(inValue);
            return retVal.Body.DONNEPRESENCEAVECIDCOURSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponse> EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.DONNEPRESENCEAVECIDCOURSAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest request) {
            return base.Channel.DONNEPRESENCEAVECIDCOURSAsync(request);
        }
        
        public System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSResponse> DONNEPRESENCEAVECIDCOURSAsync(int P_Id) {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DONNEPRESENCEAVECIDCOURSRequestBody();
            inValue.Body.P_Id = P_Id;
            return ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).DONNEPRESENCEAVECIDCOURSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponse EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.DonneUtilisateurs(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest request) {
            return base.Channel.DonneUtilisateurs(request);
        }
        
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Utilisateurs[] DonneUtilisateurs() {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequestBody();
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponse retVal = ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).DonneUtilisateurs(inValue);
            return retVal.Body.DonneUtilisateursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponse> EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.DonneUtilisateursAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest request) {
            return base.Channel.DonneUtilisateursAsync(request);
        }
        
        public System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursResponse> DonneUtilisateursAsync() {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.DonneUtilisateursRequestBody();
            return ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).DonneUtilisateursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponse EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.Add_User(EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest request) {
            return base.Channel.Add_User(request);
        }
        
        public EMPLOI_DU_TEMPS_IHM.ServiceReference1.C_Utilisateurs[] Add_User(string Nom, string Prenom) {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequestBody();
            inValue.Body.Nom = Nom;
            inValue.Body.Prenom = Prenom;
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponse retVal = ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).Add_User(inValue);
            return retVal.Body.Add_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponse> EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.Add_UserAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest request) {
            return base.Channel.Add_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserResponse> Add_UserAsync(string Nom, string Prenom) {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.Add_UserRequestBody();
            inValue.Body.Nom = Nom;
            inValue.Body.Prenom = Prenom;
            return ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).Add_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponse EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.AddPresence(EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest request) {
            return base.Channel.AddPresence(request);
        }
        
        public string AddPresence(int Id_User, int Id_Cours_Choisi) {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequestBody();
            inValue.Body.Id_User = Id_User;
            inValue.Body.Id_Cours_Choisi = Id_Cours_Choisi;
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponse retVal = ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).AddPresence(inValue);
            return retVal.Body.AddPresenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponse> EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.AddPresenceAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest request) {
            return base.Channel.AddPresenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceResponse> AddPresenceAsync(int Id_User, int Id_Cours_Choisi) {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.AddPresenceRequestBody();
            inValue.Body.Id_User = Id_User;
            inValue.Body.Id_Cours_Choisi = Id_Cours_Choisi;
            return ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).AddPresenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponse EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.SupprimePresence(EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest request) {
            return base.Channel.SupprimePresence(request);
        }
        
        public string SupprimePresence() {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequestBody();
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponse retVal = ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).SupprimePresence(inValue);
            return retVal.Body.SupprimePresenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponse> EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap.SupprimePresenceAsync(EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest request) {
            return base.Channel.SupprimePresenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceResponse> SupprimePresenceAsync() {
            EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest inValue = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequest();
            inValue.Body = new EMPLOI_DU_TEMPS_IHM.ServiceReference1.SupprimePresenceRequestBody();
            return ((EMPLOI_DU_TEMPS_IHM.ServiceReference1.WebService1Soap)(this)).SupprimePresenceAsync(inValue);
        }
    }
}
